id: PCTL-ParameterSynthesis
name: PCTL Parameter Synthesis
description: This is a tour created to describe PCTL Parameter Synthesis reduction
title_default: PCTL Parameter Synthesis
steps:
  - title: Step 1 - Begin
    element: >-
      #left .unified-panel .unified-panel-body .toolMenuContainer .toolMenu
      .toolSectionTitle.tool-menu-section-default a[href$="javascript:void(0)"]
      .name
    content: "Click here to list available tools."
    placement: bottom
  - title: Step 2 - Select tool
    element: >-
      #left > div.unified-panel > div.unified-panel-body > div > div.toolMenu >
      div:nth-child(4) > div > div > div:nth-child(2) > div:nth-child(4) > a
    content: "Click on PCTL Parameter Synthesis tool."
    placement: bottom
  - title: Step 3 - Model file
    element: 'div[tour_id="model"]'
    content:
      "Choose BCSL model file. <br>
      This tool supports only .bcs files stored in your history."
    placement: auto
  - title: Step 4 - PCTL Formula
    element: 'div[tour_id="formula"]'
    content: "Enter PCTL formula."
    placement: auto
  - title: Step 5 - Bound
    element: 'div[tour_id="bound"]'
    content: "Specify agents boundary cap (optional)."
    placement: auto
  - title: Step 6 - Insert Interval
    element: '#center .center-container .center-panel .ui-portlet .portlet-content .portlet-body .ui-form-element .ui-form-field button'
    content:
      "Please specify values interval for<br>
      each unknown parameter."
    placement: auto
  - title: Step 7 - Parameter name
    element: 'div[tour_id="regions_0|param"]'
    content: "Enter parameter name."
    placement: bottom
  - title: Step 8 - Parameter interval start
    element: 'div[tour_id="regions_0|from"]'
    content: "Enter start of the interval."
    placement: bottom
  - title: Step 9 - Parameter interval end
    element: 'div[tour_id="regions_0|to"]'
    content: "Enter end of the interval."
    placement: bottom
  - title: Step 10 - Delete Interval
    element: '#button_delete'
    content: "Option to delete your interval."
    placement: left
  - title: Step 11 - Execute
    element: '#execute'
    content: "Click the button Execute <br>to start parameter synthesis."
    placement: auto
  - title: Step 12 - Results
    element: .list-items
    content:
      "Wait until the parameter synthesis is <br>
       finished and results stored in the History."
    placement: left
