id: ProbabilitySampling
name: Probability Sampling tour
description: This is a tour created to describe TProbability Sampling generator tool.
title_default: Galaxy Tour
steps:
  - title: Step 1 - Begin
    element: >-
      #left .unified-panel .unified-panel-body .toolMenuContainer .toolMenu
      .toolSectionTitle.tool-menu-section-default a[href$="javascript:void(0)"]
      .name
    content: Click here to list available tools.
    placement: bottom
  - title: Step 2 - Select tool
    element: >-
      #left > div.unified-panel > div.unified-panel-body > div > div.toolMenu >
      div:nth-child(4) > div > div > div:nth-child(2) > div:nth-child(6) > a
    content: And click on Probability Sampling.
    placement: bottom
  - title: Step 3 - Model file
    element: 'div[tour_id="storm_file"]'
    content: >-
      Choose your model file. This tool supports only .bcs files stored in your
      history.
    placement: auto
  - title: Step 4 - Interval details
    element: 'div[tour_id="regions_0|param"]'
    content: 'Enter region parameter.'
    placement: left
  - title: Step 5 - Interval details
    element: 'div[tour_id="regions_0|from"]'
    content: 'Beginning of your interval.'
    placement: left
  - title: Step 6 - Interval details
    element: 'div[tour_id="regions_0|to"]'
    content: 'End of your interval.'
    placement: left
  - title: Step 7 - Interval details
    element: 'div[tour_id="regions_0|number"]'
    content: 'Specify numebr of samples.'
    placement: left
  - title: Step 8 - Insert interval
    element: 'div[tour_id="regions"]'
    content: Insert another reagion and fill in all necessary parameters. 
    placement: left
  - title: Step 9 - Delete interval
    element: '#button_delete'
    content: There is possibility to remove your region.
    placement: left
  - title: Step 10 - Notifications
    element: '#field-uid-187'
    content: Select an option.
    placement: right
  - title: Step 11 - Accomplishment
    element: '#execute'
    content: Just click Execute and it is done.
    placement: right
  - title: Step 12 - Results
    element: .list-items
    content: >-
      Now you have to wait while your data are processing and then you can view
      or visualize your data.
    placement: left
